/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.hong.test;

/**
 *
 * @author Abbey
 */
public class MainJFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainJFrame
     */
    public MainJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        top_lb = new javax.swing.JPanel();
        manage_lb = new javax.swing.JPanel();
        stu_manage_lb = new javax.swing.JLabel();
        apart_manage_lb = new javax.swing.JLabel();
        search_tf = new javax.swing.JTextField();
        search_bt = new javax.swing.JButton();
        table_action_label = new javax.swing.JPanel();
        main_center_lb = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        top_lb.setBackground(new java.awt.Color(255, 255, 255));
        top_lb.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 1, new java.awt.Color(204, 204, 204)));

        manage_lb.setBackground(new java.awt.Color(102, 255, 51));
        manage_lb.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        stu_manage_lb.setBackground(new java.awt.Color(255, 255, 255));
        stu_manage_lb.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        stu_manage_lb.setText("学生管理");
        stu_manage_lb.setToolTipText("学生管理");
        stu_manage_lb.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        stu_manage_lb.setOpaque(true);

        apart_manage_lb.setBackground(new java.awt.Color(255, 255, 255));
        apart_manage_lb.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        apart_manage_lb.setText("宿舍管理");
        apart_manage_lb.setToolTipText("宿舍管理");
        apart_manage_lb.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(204, 153, 0)));
        apart_manage_lb.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        apart_manage_lb.setOpaque(true);

        search_tf.setText("jTextField1");

        search_bt.setText("查找");

        javax.swing.GroupLayout manage_lbLayout = new javax.swing.GroupLayout(manage_lb);
        manage_lb.setLayout(manage_lbLayout);
        manage_lbLayout.setHorizontalGroup(
            manage_lbLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, manage_lbLayout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(stu_manage_lb, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addComponent(apart_manage_lb, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(90, 90, 90)
                .addComponent(search_tf, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(search_bt, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(87, Short.MAX_VALUE))
        );
        manage_lbLayout.setVerticalGroup(
            manage_lbLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(manage_lbLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(stu_manage_lb, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(apart_manage_lb, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(search_tf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(search_bt))
        );

        table_action_label.setBackground(new java.awt.Color(255, 255, 255));
        table_action_label.setLayout(new java.awt.CardLayout());

        javax.swing.GroupLayout top_lbLayout = new javax.swing.GroupLayout(top_lb);
        top_lb.setLayout(top_lbLayout);
        top_lbLayout.setHorizontalGroup(
            top_lbLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(manage_lb, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(table_action_label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        top_lbLayout.setVerticalGroup(
            top_lbLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(top_lbLayout.createSequentialGroup()
                .addComponent(manage_lb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(table_action_label, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(64, 64, 64))
        );

        main_center_lb.setLayout(new java.awt.CardLayout());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(top_lb, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(main_center_lb, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(top_lb, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(main_center_lb, javax.swing.GroupLayout.DEFAULT_SIZE, 394, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel apart_manage_lb;
    private javax.swing.JPanel main_center_lb;
    private javax.swing.JPanel manage_lb;
    private javax.swing.JButton search_bt;
    private javax.swing.JTextField search_tf;
    private javax.swing.JLabel stu_manage_lb;
    private javax.swing.JPanel table_action_label;
    private javax.swing.JPanel top_lb;
    // End of variables declaration//GEN-END:variables
}
