/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.hong.jframe;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.SQLException;
import java.util.Vector;

import javax.swing.JComboBox;
import javax.swing.JFrame;

import com.hong.Dao.ApartmentDao;
import com.hong.Dao.ApartmentDaoImpl;
import com.hong.Dao.StudentDao;
import com.hong.Dao.StudentDaoImpl;
import com.hong.action.AddStudentFocusListener;
import com.hong.action.FocusStartThread;
import com.hong.action.NumEngStrTextFieldInputListener;
import com.hong.action.OnlyNumberTextFieldInputListener;
import com.hong.action.TimeRun;
import com.hong.bean.Student;

/**
 *
 * @author Abbey
 */
public class AddStudentJFrame extends javax.swing.JFrame {
	
	private MainJFrame parent; 
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton ok_bt;
    private javax.swing.JLabel ruzhuriqi_label;
    private javax.swing.JLabel stu_apartment_alarm;
    private javax.swing.JComboBox<String> stu_apartment_cb;
    private javax.swing.JLabel stu_date_tf;
    private javax.swing.JLabel stu_gender_alarm;
    private JComboBox stu_gender_tf;
    private javax.swing.JLabel stu_id_alarm;
    private javax.swing.JTextField stu_id_tf;
    private javax.swing.JLabel stu_name_alarm;
    private javax.swing.JTextField stu_name_tf;
    private javax.swing.JLabel sushe_label;
    private javax.swing.JLabel title_label;
    private javax.swing.JLabel xingbie_label;
    private javax.swing.JLabel xingming_label;
    private javax.swing.JLabel xuehao_label;
    private ApartmentDaoImpl apartdao = new ApartmentDaoImpl();
    public Thread  apartThread = new Thread(new FocusStartThread(stu_apartment_alarm));
    public Thread  genderThread = new Thread(new FocusStartThread(stu_gender_alarm));
    public Thread  idThread = new Thread(new FocusStartThread(stu_id_alarm));
    public Thread  nameThread = new Thread(new FocusStartThread(stu_name_alarm));
    public Thread timeThread = new Thread(new TimeRun(this));
	
    /**
     * Creates new form AddStudentJFrame
     */
    public AddStudentJFrame( MainJFrame parent) {
        initComponents();
        this.parent = parent;
    }
    public AddStudentJFrame() {
    	Dimension   screensize   =   Toolkit.getDefaultToolkit().getScreenSize();
		int width = (int)screensize.getWidth();
		int height = (int)screensize.getHeight();
		this.setLocation(width/3, height/5);
    	initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        xuehao_label = new javax.swing.JLabel();
        xingming_label = new javax.swing.JLabel();
        sushe_label = new javax.swing.JLabel();
        xingbie_label = new javax.swing.JLabel();
        ruzhuriqi_label = new javax.swing.JLabel();
        title_label = new javax.swing.JLabel();
        stu_id_tf = new javax.swing.JTextField();
        stu_name_tf = new javax.swing.JTextField();
        Vector vec = new Vector();
        vec.addElement("女");
        vec.addElement("男");
        stu_gender_tf = new javax.swing.JComboBox(vec);
        
        stu_date_tf = new javax.swing.JLabel();
        stu_apartment_cb = new javax.swing.JComboBox(apartdao.findApartmentCode());
        stu_id_alarm = new javax.swing.JLabel();
        stu_name_alarm = new javax.swing.JLabel();
        stu_apartment_alarm = new javax.swing.JLabel();
        stu_gender_alarm = new javax.swing.JLabel();
        ok_bt = new javax.swing.JButton();
        
        AddStudentFocusListener nfl = new AddStudentFocusListener(this);
        stu_id_tf.addFocusListener(nfl);
        stu_name_tf.addFocusListener(nfl);
        stu_id_tf.addCaretListener(new OnlyNumberTextFieldInputListener());
        stu_name_tf.addCaretListener(new NumEngStrTextFieldInputListener());
        
        

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        xuehao_label.setText("学    号：");

        xingming_label.setText("姓    名：");

        sushe_label.setText("宿    舍：");

        xingbie_label.setText("性    别：");

        ruzhuriqi_label.setText("入住日期：");

        title_label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        title_label.setText("添加学生");


        stu_date_tf.setText("");
        timeThread.start();

        stu_id_alarm.setText("*请填写学号");

        stu_name_alarm.setText("*请填写姓名");

        stu_apartment_alarm.setText("*请填写宿舍");

        stu_gender_alarm.setText("*请填写性别");

        ok_bt.setText("确定");
        InsertActionListener insl = new InsertActionListener(this);
        ok_bt.addActionListener(insl);
        

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(xingming_label)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(stu_name_tf))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(xuehao_label)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(stu_id_tf))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(sushe_label)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(stu_apartment_cb, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(xingbie_label)
                                    .addComponent(ruzhuriqi_label))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(stu_date_tf, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(stu_gender_tf, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(stu_id_alarm, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(stu_gender_alarm, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(stu_apartment_alarm, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(stu_name_alarm, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(142, 142, 142)
                        .addComponent(title_label, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ok_bt, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 36, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(title_label, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(xuehao_label)
                    .addComponent(stu_id_tf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(stu_id_alarm))
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(xingming_label)
                    .addComponent(stu_name_tf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(stu_name_alarm))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sushe_label)
                    .addComponent(stu_apartment_cb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(stu_apartment_alarm))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(xingbie_label)
                    .addComponent(stu_gender_tf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(stu_gender_alarm))
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ruzhuriqi_label, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(stu_date_tf))
                .addGap(18, 18, 18)
                .addComponent(ok_bt)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 23, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
/*    public static void main(String args[]) {
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddStudentJFrame().setVisible(true);
            }
        });
    }*/

    
  //添加action
    class InsertActionListener implements ActionListener{
    	AddStudentJFrame ajf;
    	public InsertActionListener(JFrame jf)
    	{
    		ajf = (AddStudentJFrame) jf;
    	}
   	@Override
   	public void actionPerformed(ActionEvent e) {
   		// TODO Auto-generated method stub
   		if(stu_name_tf.getText().equals("") || stu_apartment_cb.getSelectedItem().equals("请选择宿舍！") || stu_id_tf.getText().equals(""))
   			System.out.println("空");
   		else
   		{	
	   		int stu_id = Integer.parseInt(stu_id_tf.getText());
	   		String stu_name = stu_name_tf.getText();
	   		String stu_apart_name =  stu_apartment_cb.getSelectedItem()+"";
	   		String stu_gender = stu_gender_tf.getSelectedItem()+"";
	   		String stu_date = stu_date_tf.getText();
	   		StudentDaoImpl studao = new StudentDaoImpl();
	   		Student student = new Student();
	   		student.setStu_id(stu_id);
	   		student.setStu_name(stu_name);
	   		student.setStu_apart_name(stu_apart_name);
	   		student.setStu_gender(stu_gender);
	   		student.setStu_date(stu_date);
	   		studao.insertStudent(student);
	   		//ajf.setVisible(false);
	   		try {
				parent.getStudentTablePanel().getStu_table_model().showResult(studao.findAllStudents());
				parent.getApartmentTablePanel().getApart_table_model().showResult(apartdao.findAllApartment());
			} catch (SQLException e1) {
				// TODO Auto-generated catch block
				e1.printStackTrace();
			}
   		}
   	}}


	public javax.swing.JLabel getStu_apartment_alarm() {
		return stu_apartment_alarm;
	}

	public void setStu_apartment_alarm(javax.swing.JLabel stu_apartment_alarm) {
		this.stu_apartment_alarm = stu_apartment_alarm;
	}

	public javax.swing.JLabel getStu_date_tf() {
		return stu_date_tf;
	}

	public void setStu_date_tf(javax.swing.JLabel stu_date_tf) {
		this.stu_date_tf = stu_date_tf;
	}

	public javax.swing.JLabel getStu_gender_alarm() {
		return stu_gender_alarm;
	}

	public void setStu_gender_alarm(javax.swing.JLabel stu_gender_alarm) {
		this.stu_gender_alarm = stu_gender_alarm;
	}

	public JComboBox getStu_gender_tf() {
		return stu_gender_tf;
	}

	public void setStu_gender_tf(JComboBox stu_gender_tf) {
		this.stu_gender_tf = stu_gender_tf;
	}

	public javax.swing.JLabel getStu_id_alarm() {
		return stu_id_alarm;
	}

	public void setStu_id_alarm(javax.swing.JLabel stu_id_alarm) {
		this.stu_id_alarm = stu_id_alarm;
	}

	public javax.swing.JTextField getStu_id_tf() {
		return stu_id_tf;
	}

	public void setStu_id_tf(javax.swing.JTextField stu_id_tf) {
		this.stu_id_tf = stu_id_tf;
	}

	public javax.swing.JLabel getStu_name_alarm() {
		return stu_name_alarm;
	}

	public void setStu_name_alarm(javax.swing.JLabel stu_name_alarm) {
		this.stu_name_alarm = stu_name_alarm;
	}

	public javax.swing.JTextField getStu_name_tf() {
		return stu_name_tf;
	}

	public void setStu_name_tf(javax.swing.JTextField stu_name_tf) {
		this.stu_name_tf = stu_name_tf;
	}
}
