/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.hong.jpanel;

import java.sql.SQLException;

import javax.swing.JScrollPane;
import javax.swing.JTable;

import com.hong.Dao.ApartmentDao;
import com.hong.Dao.ApartmentDaoImpl;
import com.hong.action.JTableDeleteMouseAction;
import com.hong.action.JTableUpdateMouseAction;
import com.hong.jtable_model.ApartmentTableModel;

/**
 *
 * @author Abbey
 */
public class ApartmentTablePanel extends TablePanel {
    private JScrollPane jScrollPane1;
    private ApartmentTableModel apart_table_model;
    private ApartmentDaoImpl apart_dao = new ApartmentDaoImpl();
    
    /**
     * Creates new form StudentTablePanel
     */
    public ApartmentTablePanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
    	setName("apartment");

        jScrollPane1 = new javax.swing.JScrollPane();
        setTable(new javax.swing.JTable());
        apart_table_model = new ApartmentTableModel();
        getTable().setModel(apart_table_model);
        JTableUpdateMouseAction l = new JTableUpdateMouseAction(this);
        getTable().addMouseListener(l);
        
        JTableDeleteMouseAction l1 = new JTableDeleteMouseAction(this);
        getTable().addMouseListener(l1);
        jScrollPane1.setViewportView(getTable());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );
        
        try {
			apart_table_model.showResult(apart_dao.findAllApartment());
		} catch (SQLException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
    }// </editor-fold>//GEN-END:initComponents

	public ApartmentTableModel getApart_table_model() {
		return apart_table_model;
	}
    
}
