/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.hong.jpanel;

import java.sql.SQLException;

import com.hong.Dao.StudentDao;
import com.hong.Dao.StudentDaoImpl;
import com.hong.action.JTableDeleteMouseAction;
import com.hong.action.JTableUpdateMouseAction;
import com.hong.jtable_model.StudentTableModel;

/**
 *
 * @author Abbey
 */
public class StudentTablePanel extends TablePanel {

    private javax.swing.JScrollPane jScrollPane1;
    private StudentTableModel stu_table_model = new StudentTableModel();
    private StudentDaoImpl stu_dao = new StudentDaoImpl();
    
    /**
     * Creates new form StudentTablePanel
     */
    public StudentTablePanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
    	setName("student");

        jScrollPane1 = new javax.swing.JScrollPane();
        setTable(new javax.swing.JTable());
        getTable().setModel(stu_table_model);
        JTableUpdateMouseAction l = new JTableUpdateMouseAction(this);
        getTable().addMouseListener(l);
        JTableDeleteMouseAction l1 = new JTableDeleteMouseAction(this);
        getTable().addMouseListener(l1);
        jScrollPane1.setViewportView(getTable());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );
        try {
			stu_table_model.showResult(stu_dao.findAllStudents());
		} catch (SQLException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
    }// </editor-fold>//GEN-END:initComponents

	public StudentTableModel getStu_table_model() {
		return stu_table_model;
	}
}
